### ISSUE TITLE
Not working not sure why.

### ISSUE THREAD

**Issue by 77920** [Crypto90/Wolcen-Socket-Roller#3]
Running as admin and in Window Mode 1366x768 i've watched it go over support3 , support3 , support 3 on catalyst now over 3000 times rolls with no success... What do you recommend to have success. Great work BTW.

**Comment by Crypto90** [comment]
Does the tool does not work for you correctly, or do you have no sucess with getting the rolls?
Does it rolls over a match? If so, try increase the sleep time to 200-300 ms.
You can also enable logging the scan areas (log screenshots) to keep track whats happening.

If you just have no luck, I saw catalyst is really hard to get it to 3x support3.

You can also try increasing your game resolution. Larger game resolution = better color detection.

**Comment by 77920** [comment]
Works alot better with Logging Screenshots checked off :) i've had success! Nice work!

**Comment by Crypto90** [comment]
Alright, so I'm closing this issue. Feel free to open a new one if you encounter any issue.
