### ISSUE TITLE
Still Work? 

### ISSUE THREAD

**Issue by tuutuu803** [Crypto90/Wolcen-Socket-Roller#4]
Thank you for your contribution. You probably stopped playing the game but does this still work?

**Comment by Crypto90** [comment]
It should still work yes.
I have some reports that players still using it, so it did not break in the time. It should not break as long as the game socket reroll window changes optically with the GUI ingame.
I have stopped playing but if something breaks, I can fix it in the future too.

**Comment by tuutuu803** [comment]
Didn't think you would reply! Thank you for the update haha
 
 
  On Tue, Jan 26, 2021 at 3:49 AM, Crypto90<notifications@github.com> wrote:   


It should still work yes.
I have some reports that players still using it, so it did not break in the time. It should not break as long as the game socket reroll window changes optically with the GUI ingame.
I have stopped playing but if something breaks, I can fix it in the future too.
